package com.moha.ebook.entities;

public enum Categorie {
    HORROR, ACTION, COMEDY, DRAMA, ROMANCE, FANTASY, SCIENCE_FICTION, THRILLER, MYSTERY, ADVENTURE, BIOGRAPHY, HISTORY, CRIME, ANTHOLOGY, CLASSICS, DIARY, DICTIONARY, ENCYCLOPEDIA, GUIDE, POETRY, RELIGION, SCIENCE, SELF_HELP, TRAVEL, YOUNG_ADULT, OTHERS
}
